-- CreateTable
CREATE TABLE "dvf_data" (
    "id" SERIAL NOT NULL,
    "No disposition" INTEGER,
    "Date mutation" DATE,
    "Nature mutation" VARCHAR(50),
    "Valeur fonciere" INTEGER,
    "No voie" INTEGER,
    "B/T/Q" VARCHAR(10),
    "Type de voie" VARCHAR(50),
    "Code voie" VARCHAR(10),
    "Voie" VARCHAR(100),
    "Code postal" INTEGER,
    "Commune" VARCHAR(100),
    "Code departement" VARCHAR(10),
    "Code commune" INTEGER,
    "Prefixe de section" DOUBLE PRECISION,
    "Section" VARCHAR(10),
    "No plan" INTEGER,
    "No Volume" VARCHAR(50),
    "1er lot" VARCHAR(50),
    "Surface Carrez du 1er lot" VARCHAR(50),
    "2eme lot" VARCHAR(50),
    "Surface Carrez du 2eme lot" VARCHAR(50),
    "3eme lot" VARCHAR(50),
    "Surface Carrez du 3eme lot" VARCHAR(50),
    "4eme lot" VARCHAR(50),
    "Surface Carrez du 4eme lot" VARCHAR(50),
    "5eme lot" VARCHAR(50),
    "Surface Carrez du 5eme lot" VARCHAR(50),
    "Nombre de lots" INTEGER,
    "Code type local" INTEGER,
    "Type local" VARCHAR(50),
    "Identifiant local" DOUBLE PRECISION,
    "Surface reelle bati" INTEGER,
    "Nombre pieces principales" INTEGER,
    "Nature culture" VARCHAR(50),
    "Nature culture speciale" VARCHAR(50),
    "Surface terrain" INTEGER,

    CONSTRAINT "dvf_data_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "stg_dvf" (
    "id" INTEGER,
    "no_disposition" INTEGER,
    "date_mutation" DATE,
    "nature_mutation" VARCHAR(50),
    "valeur_fonciere" BIGINT,
    "no_voie" INTEGER,
    "b_t_q" VARCHAR(10),
    "type_de_voie" VARCHAR(50),
    "code_voie" VARCHAR(10),
    "voie" VARCHAR(100),
    "code_postal" INTEGER,
    "commune" VARCHAR(100),
    "code_departement" VARCHAR(10),
    "code_commune" INTEGER,
    "prefixe_de_section" DOUBLE PRECISION,
    "section" VARCHAR(10),
    "no_plan" INTEGER,
    "no_volume" VARCHAR(50),
    "premier_lot" VARCHAR(50),
    "surface_carrez_du_1er_lot" DECIMAL,
    "deuxieme_lot" VARCHAR(50),
    "surface_carrez_du_2eme_lot" DECIMAL,
    "troiseme_lot" VARCHAR(50),
    "surface_carrez_du_3eme_lot" DECIMAL,
    "quatrieme_lot" VARCHAR(50),
    "surface_carrez_du_4eme_lot" DECIMAL,
    "cinquieme_lot" VARCHAR(50),
    "surface_carrez_du_5eme_lot" DECIMAL,
    "nombre_de_lots" INTEGER,
    "code_type_local" INTEGER,
    "type_local" VARCHAR(50),
    "surface_reelle_bati" INTEGER,
    "nombre_pieces_principales" INTEGER,
    "nature_culture" VARCHAR(50),
    "nature_culture_speciale" VARCHAR(50),
    "surface_terrain" INTEGER
);
