name: "dbt_homepedia"
config-version: 2
version: "1.2.0"

profile: "homepedia"

model-paths: ["models"]
analysis-paths: ["analyses"]

models:
  dbt_homepedia:
    +materialized: table
    1_staging:
      +materialized: table
      +schema: staging
    homepedia:
      +materialized: table
      dvf_treated:
        post-hook:
          - "ALTER TABLE {{ this }} ADD PRIMARY KEY (id);"
