#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Vérifiez si des fichiers dans le dossier API ont été modifiés
if git diff --cached --name-only | grep "^Api/"; then
  cd Api
  npm run lint:fix
  npm run type-check

  # Vérifiez s'il y a des erreurs après le lint et le type-check
  if [ $? -ne 0 ]; then
    echo "Des erreurs ont été trouvées. Veuillez les corriger avant de commiter."
    exit 1
  fi

  git add .
fi